# -*- coding: utf-8 -*-
"""Configuration 랜덤 네트워크 모델 클래스 구현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bza0J6NahkUhy1kHLuWld7LSCBB-m4Vo
"""

class Configuration:

  ''' 생성자 함수 '''
  def __init__(self, G, n):

    if G.number_of_nodes() == 0:
      raise ValueError("입력 그래프 G가 비어 있습니다.")

    else:
      self.G = G

      self.G_degree = self.G.degree()
      self.degree_seq = [d for _, d in self.G_degree]

      if len(self.degree_seq) == 0:
        raise ValueError("degree 배열 리스트가 비어 있습니다.")

      print("original network 노드 개수 :", len(self.G.nodes()), "엣지 개수", len(self.G.edges()))

    self.original_degree_dist = None
    self.original_degree_dist_bins = None

    if not isinstance(n, int) or n <= 0:
      raise ValueError("n은 1 이상의 정수여야 합니다.")
    else:
      self.num_simulations = n

    self.config_models = []

    self.config_degree_dists = []


  ''' Configuration 모델 생성하는 함수 '''
  def create_config_graph(self):

    stub_list = []
    for node, degree in enumerate(self.degree_seq):
      stub_list.extend([node]*degree)

    N = len(stub_list)

    if N == 0:
      raise ValueError("stub list가 비어 있습니다.")

    elif N % 2 != 0 : # stub_list 길이가 짝수여야 함
      stub_list.append(stub_list[-1])

    random.shuffle(stub_list)

    config_graph = nx.Graph()
    config_graph.add_nodes_from(range(len(self.degree_seq)))

    while len(stub_list) > 1:

      node1 = stub_list.pop()
      node2 = stub_list.pop()

      config_graph.add_edge(node1, node2)

    return config_graph

  ''' n번 반복해서 Configuration 모델 생성하는 함수 '''
  def n_repeat(self):
    for i in range(self.num_simulations):

      temp_net = self.create_config_graph()

      simple_net = nx.Graph(temp_net)
      self.config_models.append(simple_net)

    print("configuration 모델 반복 생성 완료했습니다.")

    return self.config_models


  ''' 히스토그램 그리기 앞서 dist 계산하는 함수'''
  def cal_dist(self):
    self.original_degree_dist = np.histogram(self.degree_seq, bins = range(max(self.degree_seq)+2), density = True)[0]

    if not self.config_models:
      raise RuntimeError("config model 리스트가 비어 있습니다.")

    else:
      for config_graph in self.config_models:
        cm_degrees = [d for _, d in config_graph.degree()]

        config_dist = np.histogram(cm_degrees, bins = range(max(self.degree_seq)+2), density = True)[0]

        self.config_degree_dists.append(config_dist)

    if max(cm_degrees) > max(self.degree_seq):
      raise ValueError("config model의 차수가 원본 그래프보다 큽니다.")


  ''' 히스토그램 그리는 함수 '''
  def draw_histogram(self):
    fig, ax = plt.subplots(1, 1, figsize = (8, 5))

    ax.bar(range(len(self.original_degree_dist)), self.original_degree_dist, alpha = 0.7, color = 'blue', label='Uganda Network', width = 0.4, align = 'center')

    mean_dist = np.mean(self.config_degree_dists, axis = 0)
    ax.bar(np.arange(len(self.original_degree_dist))+0.4, mean_dist, alpha = 0.7, color = '#E6B8AF', label='Configuration Model', width = 0.4, align = 'center')

    ax.set_xlabel(r'degree($k$)', fontsize=15)
    ax.set_ylabel(r'$P(k)$', fontsize = 15)

    plt.legend(fontsize=12)
    plt.show()

