# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hs4hqF7rRTMMfz8EXwtnrbutim8xzOAk
"""

import networkx as nx
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
import itertools
import seaborn as sns

from models.er import ER
from models.configuration import Configuration
from models.chung_lu import chung_lu
from models.ba import BA

def load_graph():
  nodes = pd.read_csv("data/uganda_health_nodes.csv")
  edges = pd.read_csv("data/uganda_health_edges.csv")
  G = nx.from_pandas_edgelist(edges, source="Source", target="Target")
  return G


if __name__ == "__main__":
    print("=== Loading network ===")
    G = load_graph()

    print("\n=== Generating ER model histogram ===") 
    E = ER(G, 100)
    E.n_repeat()
    E.cal_dist()
    E.draw_histogram()

    print("\n=== Generating Configuration model histogram ===")
    config_model = Configuration(G, 100)
    config_model.n_repeat()
    config_model.cal_dist()
    config_model.draw_histogram()

    print("\n=== Generating Chung-Lu model histogram ===")
    cl_model = chung_lu(G, num_simul=100)
    cl_model.generate_ensemble()
    cl_model.calculate_distributions()
    cl_model.draw_comparison()

    print("\n=== Generating BA model histogram ===")
    B = BA(G, 100)
    B.n_repeat()
    B.cal_dist()
    B.draw_histogram()
    a_ori, beta_ori = B.fit_beta(sample_graph=G)
    print("original beta =", beta_ori)
    a_hat, beta_ba = B.fit_beta()
    print("BA model beta =", beta_ba)