# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hs4hqF7rRTMMfz8EXwtnrbutim8xzOAk
"""

import networkx as nx
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# 추가해야 하는 모듈 없나 체크

from models.er import ERGraph # 클래스 이름 바꾸기
from models.configuration import Configuration
from models.chung_lu import ChungLuModel # 클래스 이름 바꾸기
from models.ba import BaModel # 클래스 이름 바꾸기

from analysis.degree_centrality import DegreeCentrality # 클래스 이름 바꾸기
from analysis.closeness_centrality import ClosenessCentrality # 클래스 이름 바꾸기


def load_graph():
  nodes = pd.read_csv("data/uganda_health_nodes.csv") # 꼭 data 폴더 속 해당 이름의 파일로 있어야 함
  edges = pd.read_csv("data/uganda_health_edges.csv")
  G = nx.from_pandas_edgelist(edges, source="Source", target="Target")
  return G


if __name__ == "__main__":
    print("=== Loading network ===")
    G = load_graph()

    print("\n=== Generating ER model histogram ===")  # 해당 클래스 이름으로 함수 호출
    er_graph = ERGraph(n=100, p=0.05).generate()

    print("\n=== Generating Configuration model histogram ===")
    config_model = Configuration(G, 100)
    config_model.n_repeat()
    config_model.cal_dist()
    config_model.draw_histogram()

    print("\n=== Generating Chung-Lu model histogram ===")
    chung_graph = ChungLuModel(G).generate()

    print("\n=== Generating BA model histogram ===")
    ba_graph = BaModel(n=100, m=2).generate()

    print("\n=== Calculating Degree Centrality ===")
    degree_scores = DegreeCentrality(G).calculate()

    print("\n=== Calculating Closeness Centrality ===")
    closeness_scores = ClosenessCentrality(G).calculate()

    print("\nDegree Centrality:", degree_scores)
    print("Closeness Centrality:", closeness_scores)