# -*- coding: utf-8 -*-
"""중심성 지표 비교 - closeness centerailty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLn2Wf6rc48ImTZW8r3dsB9w9lH5BTMT
"""

import pandas as pd
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("uganda health data", header=None)
G_actual = nx.from_pandas_edgelist(df, source=0, target=1)
print("노드:", G_actual.number_of_nodes(), "엣지:", G_actual.number_of_edges())

from er_class import ER
from configuration_class import Configuration
from chung_lu_class import chung_lu_model

er = ER(G_actual, n=1)
er_models = er.n_repeat() # Call n_repeat to generate models
G_er = er_models[0]       # Access the first model from the returned list

config = Configuration(G_actual, n=1)
config_models = config.n_repeat() # Call n_repeat to generate models
G_config = config_models[0]       # Access the first model from the returned list

cl = chung_lu_model("uganda health data", num_simul=1)
cl.load_graph()
cl.generate_ensemble()
G_cl = cl.chunglu_models[0]

# 중심성 계산 (closeness)
def get_closeness(G):
    return np.array(list(nx.closeness_centrality(G).values()))

# --- 3개 모델 Subplot 비교 ---
def compare_centrality_subplots(G_actual, G_er, G_config, G_cl):

    # closeness 계산
    c_actual = get_closeness(G_actual)
    c_er     = get_closeness(G_er)
    c_config = get_closeness(G_config)
    c_cl     = get_closeness(G_cl)

    COMMON_BINS = np.linspace(0.25, 0.65, 31) # 30개 구간 (31개 경계선)

    # subplot 생성
    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

    # ER
    axes[0].hist(c_actual, bins=COMMON_BINS, alpha=0.6, color = "mediumblue", label="Actual", density=True)
    axes[0].hist(c_er, bins=COMMON_BINS, alpha=0.6, color = "greenyellow", label="ER", density=True)
    axes[0].set_title("Actual vs ER")
    axes[0].set_xlabel("Closeness")
    axes[0].grid(True, linestyle='--', alpha=0.5)
    axes[0].legend()

    # Configuration
    axes[1].hist(c_actual, bins=COMMON_BINS, alpha=0.6, color = "mediumblue", label="Actual", density=True)
    axes[1].hist(c_config, bins=COMMON_BINS, alpha=0.6, color = "greenyellow", label="Configuration", density=True)
    axes[1].set_title("Actual vs Configuration")
    axes[1].set_xlabel("Closeness")
    axes[1].grid(True, linestyle='--', alpha=0.5)
    axes[1].legend()

    # Chung-Lu
    axes[2].hist(c_actual, bins=COMMON_BINS, alpha=0.6, color = "mediumblue", label="Actual", density=True)
    axes[2].hist(c_cl, bins=COMMON_BINS, alpha=0.6, color = "greenyellow", label="Chung-Lu", density=True)
    axes[2].set_title("Actual vs Chung-Lu")
    axes[2].set_xlabel("Closeness")
    axes[2].grid(True, linestyle='--', alpha=0.5)
    axes[2].legend()

    fig.suptitle("Closeness Centrality Comparison Across Models", fontsize=16)
    plt.tight_layout()
    plt.show()

compare_centrality_subplots(G_actual, G_er, G_config, G_cl)

def boxplot_compare(G_actual, G_er, G_config, G_cl):
    # closeness 계산
    c_actual = list(nx.closeness_centrality(G_actual).values())
    c_er     = list(nx.closeness_centrality(G_er).values())
    c_config = list(nx.closeness_centrality(G_config).values())
    c_cl     = list(nx.closeness_centrality(G_cl).values())

    data = [c_actual, c_er, c_config, c_cl]
    labels = ["Actual", "ER", "Config", "Chung-Lu"]

    plt.figure(figsize=(10,6))
    plt.boxplot(data, labels=labels, patch_artist=True)

    plt.title("Closeness Centrality Comparison")
    plt.ylabel("Closeness Centrality")
    plt.show()

boxplot_compare(G_actual, G_er, G_config, G_cl)

def boxplot_closeness_compare_with_ylim(G_actual, G_er, G_config, G_cl):

    # Closeness Centrality 계산
    c_actual = list(nx.closeness_centrality(G_actual).values())
    c_er     = list(nx.closeness_centrality(G_er).values())
    c_config = list(nx.closeness_centrality(G_config).values())
    c_cl     = list(nx.closeness_centrality(G_cl).values())

    data = [c_actual, c_er, c_config, c_cl]
    labels = ["Actual", "ER", "Config", "Chung-Lu"]

    plt.figure(figsize=(10, 6))
    plt.boxplot(data, labels=labels, patch_artist=True)

    # Y축 스케일(범위) 설정
    # Closeness 값이 보통 0.3 ~ 0.6 사이에 집중되므로 이 범위를 설정합니다.
    plt.ylim(0.2, 0.65) # Y축의 최소를 0.2, 최대를 0.65로 설정

    plt.ylabel("Closeness Centrality", fontsize=14)
    plt.xlabel("Network Model", fontsize=12)
    plt.grid(axis='y', linestyle='--', alpha=0.6)
    plt.show()

boxplot_closeness_compare_with_ylim(G_actual, G_er, G_config, G_cl)

import networkx as nx
import matplotlib.pyplot as plt

# -----------------------------
# 공통 스타일 박스플롯 (closeness 전용)
# -----------------------------
def plot_closeness_boxplot(values_list, labels, ylim=None, savepath=None):

    colors = ["#6baed6", "#9ecae1", "#c7e9b4", "#fdd0a2"]  # 부드러운 4색 팔레트

    plt.figure(figsize=(10, 6))
    bp = plt.boxplot(
        values_list,
        labels=labels,
        patch_artist=True,
        showfliers=False,
        widths=0.6
    )

    # 박스 색상 + 라인 통일
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_edgecolor("#4c4c4c")
        patch.set_linewidth(1.2)

    for median in bp['medians']:
        median.set_color("#d62728")
        median.set_linewidth(2.2)

    for whisker in bp['whiskers']:
        whisker.set_color("#4c4c4c")
        whisker.set_linewidth(1.2)

    for cap in bp['caps']:
        cap.set_color("#4c4c4c")
        cap.set_linewidth(1.2)

    # ---- 라벨 크게 ----
    plt.xlabel("Network Model", fontsize=15)
    plt.ylabel("Closeness Centrality", fontsize=17)
    plt.xticks(fontsize=14)
    plt.yticks(fontsize=13)

    if ylim:
        plt.ylim(*ylim)

    plt.grid(axis='y', linestyle='--', alpha=0.6)
    plt.tight_layout()

    if savepath:
        plt.savefig(savepath, dpi=300)
        plt.close()
    else:
        plt.show()

# -----------------------------
# closeness 중앙성 계산 + 플롯
# -----------------------------
def boxplot_closeness_same_style(G_actual, G_er, G_config, G_cl, savepath=None):

    c_actual = list(nx.closeness_centrality(G_actual).values())
    c_er     = list(nx.closeness_centrality(G_er).values())
    c_config = list(nx.closeness_centrality(G_config).values())
    c_cl     = list(nx.closeness_centrality(G_cl).values())

    values_list = [c_actual, c_er, c_config, c_cl]
    labels = ["Original", "ER", "Config", "Chung-Lu"]

    plot_closeness_boxplot(
        values_list,
        labels,
        ylim=(0.2, 0.65),
        savepath=savepath
    )

boxplot_closeness_same_style(G_actual, G_er, G_config, G_cl, "closeness_boxplot.png")

boxplot_closeness_same_style(G_actual, G_er, G_config, G_cl)

"""# Config: 차수 분포 보존 → Actual과 가장 유사한 closeness 분포.

# ER: 무작위 연결 → 거리 다양성 낮고 closeness가 좁게 몰림.

# Chung-Lu: 기대차수만 맞춤 → 실제 경로 구조 재현 실패, closeness 낮음.
"""