# -*- coding: utf-8 -*-
"""Chung-lu 랜덤 네트워크 모델 클래스 구현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4u_5os3w1Z6XDtFkS9Fs3JsTs5zhX70
"""

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import random
import pandas as pd

"""# 우간다"""

class chung_lu_model:
  def __init__(self, csv_file, num_simul=50):
    self.csv_file = csv_file
    self.num_simul = num_simul
    self.actual_graph = None
    self.actual_degrees = None
    self.actual_dist = None
    self.chunglu_models = []
    self.cl_dists = []
    self.actual_G = None

  # 그래프 로드
  def load_graph(self):
        self.actual_degrees = None
        self.actual_G = None

        try:
            df = pd.read_csv(self.csv_file, header=None)
            self.actual_G = nx.Graph()

            all_nodes = set(list(df.iloc[:, 0].dropna()) + list(df.iloc[:, 1].dropna()))
            self.actual_G.add_nodes_from(all_nodes)

            for i in range(len(df)):
              node1 = df.iloc[i, 0]
              node2 = df.iloc[i, 1]

              if node1 != node2 and pd.notna(node1) and pd.notna(node2):
                self.actual_G.add_edge(node1, node2)

            self.actual_degrees = [d for _, d in self.actual_G.degree()]

        except FileNotFoundError:
            print(f"오류: 파일을 찾을 수 없습니다. 경로를 확인해주세요: {self.csv_file}")
            self.actual_degrees = None

        except Exception as e:
            print(f"데이터 처리 중 오류 발생: {e}")
            self.actual_degrees = None

  # 청루 모형 제작
  def create_chung_lu_graph(self):

    degrees = [int(d) for d in self.actual_degrees]
    total_degree = sum(degrees)
    n = len(degrees)

    G = nx.Graph()
    G.add_nodes_from(range(n))

    for i in range(n) :
        for j in range(i+1,n) :
            p_ij = degrees[i] * degrees[j] / total_degree
            p_ij = min(1.0, p_ij)

            if random.random() < p_ij :
                G.add_edge(i, j)
    return G

  # ensemble 비교
  def generate_ensemble(self):
          for _ in range(self.num_simul):
              temp_net = self.create_chung_lu_graph()
              simple_net = nx.Graph(temp_net)
              self.chunglu_models.append(simple_net)

  # P(k) 계산
  def calculate_distributions(self):

      max_degree = max(self.actual_degrees)
      bins_range = range(max_degree + 2)

      self.actual_dist = np.histogram(
          self.actual_degrees,
          bins=bins_range,
          density=True
      )[0]

      self.cl_dists = []
      for g in self.chunglu_models:
          cm_degrees = [d for _, d in g.degree()]
          chunglu_dist = np.histogram(
              cm_degrees,
              bins=bins_range,
              density=True
          )[0]
          self.cl_dists.append(chunglu_dist)

  # 시각화
  def draw_comparison(self):
      fig, ax = plt.subplots(1, 1, figsize = (8, 5))

      ax.bar(
          range(len(self.actual_dist)),
          self.actual_dist,
          alpha = 0.7, color = 'blue', label='Uganda Network', width = 0.4, align = 'center'
      )

      mean_dist = np.mean(self.cl_dists, axis=0)
      ax.bar(
          np.arange(len(mean_dist)) + 0.3,
          mean_dist,
          alpha = 0.7, color = '#E6B8AF', label='Chung-lu Model', width = 0.4, align = 'center'
      )

      ax.set_xlabel(r'degree($k$)', fontsize=15)
      ax.set_ylabel(r'$P(k)$', fontsize = 15)

      plt.legend(fontsize=12)
      plt.show()

# 실행
cl_model = chung_lu_model('/Users/yoonsubin/Documents/2025/network_pj/data/uganda health data', num_simul=100)

cl_model.load_graph()
cl_model.generate_ensemble()
cl_model.calculate_distributions()

cl_model.draw_comparison()

