# -*- coding: utf-8 -*-
"""Chung-lu 랜덤 네트워크 모델 클래스 구현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4u_5os3w1Z6XDtFkS9Fs3JsTs5zhX70
"""
class chung_lu:
  def __init__(self, G, num_simul=50):
        # if not isinstance(G, nx.Graph):
        #     raise TypeError("G는 NetworkX Graph 객체여야 합니다.")
            
        if G.number_of_nodes() == 0:
            raise ValueError("입력 그래프 G가 비어 있습니다.")

        self.num_simul = num_simul
        self.actual_G = G
        
        self.actual_degrees = [d for _, d in G.degree()]
        
        if not self.actual_degrees:
             raise ValueError("차수 시퀀스를 추출할 수 없습니다.")
             
        self.actual_dist = None
        self.chunglu_models = []
        self.cl_dists = []

  # 청루 모형 제작
  def create_chung_lu_graph(self):

    degrees = [int(d) for d in self.actual_degrees]
    total_degree = sum(degrees)
    n = len(degrees)

    cl_G = nx.Graph()
    cl_G.add_nodes_from(range(n))

    for i in range(n) :
        for j in range(i+1,n) :
            p_ij = degrees[i] * degrees[j] / total_degree
            p_ij = min(1.0, p_ij)

            if random.random() < p_ij :
                cl_G.add_edge(i, j)
    return cl_G

  # ensemble 비교
  def generate_ensemble(self):
            for _ in range(self.num_simul):
                temp_net = self.create_chung_lu_graph()
                simple_net = nx.Graph(temp_net)
                self.chunglu_models.append(simple_net)

  # P(k) 계산
  def calculate_distributions(self):

      max_degree = max(self.actual_degrees)
      bins_range = range(max_degree + 2)

      self.actual_dist = np.histogram(
          self.actual_degrees,
          bins=bins_range,
          density=True
      )[0]

      self.cl_dists = []
      for g in self.chunglu_models:
          cm_degrees = [d for _, d in g.degree()]
          chunglu_dist = np.histogram(
              cm_degrees,
              bins=bins_range,
              density=True
          )[0]
          self.cl_dists.append(chunglu_dist)

  # 시각화
  def draw_comparison(self):
      fig, ax = plt.subplots(1, 1, figsize = (8, 5))

      ax.bar(
          range(len(self.actual_dist)),
          self.actual_dist,
          alpha = 0.7, color = 'blue', label='Uganda Network', width = 0.4, align = 'center'
      )

      mean_dist = np.mean(self.cl_dists, axis=0)
      ax.bar(
          np.arange(len(mean_dist)) + 0.3,
          mean_dist,
          alpha = 0.7, color = '#E6B8AF', label='Chung-lu Model', width = 0.4, align = 'center'
      )

      ax.set_xlabel(r'degree($k$)', fontsize=15)
      ax.set_ylabel(r'$P(k)$', fontsize = 15)

      plt.legend(fontsize=12)
      plt.show()


